/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#fff8f8",
        "on-secondary-container": "#006e70",
        "primary": "#b40065",
        "outline-variant": "#e3bdc7",
        "surface-variant": "#fadbe3",
        "error": "#ba1a1a",
        "inverse-surface": "#3e2b31",
        "on-error": "#ffffff",
        "surface": "#fff8f8",
        "on-tertiary-container": "#fefcff",
        "primary-fixed": "#ffd9e3",
        "on-primary-fixed": "#3e001f",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#002020",
        "surface-container": "#ffe8ed",
        "on-surface-variant": "#5b3f48",
        "surface-container-low": "#fff0f3",
        "tertiary-fixed-dim": "#a5c8ff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#ffb0ca",
        "outline": "#8f6e78",
        "inverse-on-surface": "#ffecf0",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#b90068",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#5af8fb",
        "secondary-container": "#56f5f8",
        "on-primary-container": "#fffbff",
        "on-secondary-fixed-variant": "#004f51",
        "on-surface": "#28171c",
        "tertiary": "#005cab",
        "secondary-fixed-dim": "#2ddbde",
        "secondary": "#00696b",
        "surface-dim": "#f1d2da",
        "tertiary-fixed": "#d4e3ff",
        "on-tertiary-fixed": "#001c3a",
        "surface-container-high": "#ffe1e8",
        "inverse-primary": "#ffb0ca",
        "on-error-container": "#93000a",
        "on-background": "#28171c",
        "primary-container": "#e10080",
        "tertiary-container": "#0075d6",
        "surface-bright": "#fff8f8",
        "on-primary-fixed-variant": "#8d004e",
        "on-tertiary-fixed-variant": "#004786",
        "surface-container-highest": "#fadbe3"
      },
      spacing: {
        "sticker-padding": "12px",
        "gutter-collage": "16px",
        "margin-page": "40px",
        "stack-overlap": "-24px"
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "accent": ["Be Vietnam Pro", "sans-serif"],
      },
       borderRadius: {
        "none": "0",
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
